# Generated by Django 5.1.4 on 2026-03-10 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='starting_money',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='base_bet',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='starting_money',
            field=models.IntegerField(default=100),
        ),
    ]
